from abc import ABC, abstractmethod


class BaseLLMClient(ABC):
    """Provider-agnostic contract used by CommitGenerationService."""

    @abstractmethod
    def generate(self, prompt: str) -> str:
        """Return raw text generated by the selected LLM provider."""
        raise NotImplementedError
